### ISSUE TITLE
add lexical domain to result

### ISSUE THREAD

**Issue by kengz** [moos/wordpos#11]
as detailed here [https://github.com/Planeshifter/node-wordnet-magic#lexdomain],

>The lexical domain of the synset. Each domain category is composed of the word type followed by a dot and then the category name. WordNet has implemented the following domain categories:

For example 'dance' gives lexdomain 'noun.act'

**Comment by moos** [comment]
This would be a simple matter of mapping the 'lexFilenum' attribute to the [lexnames](https://wordnet.princeton.edu/wordnet/man/lexnames.5WN.html).

An example of how you intend to use this would help in prioritizing this work.

**Comment by kengz** [comment]
Oh thanks. Though it'd be sweet if we can get the words directly than having to manually translate into the lexnames.

A use case would be for a module to know if it's supposed to perform a function. For example inputting "bot switch on the lights", after tokenizing and some string cleaning, if a token belongs to "noun.act" or "verb.change"  in this case it will invoke the function if it is recognized (function = switch on, argument = lights in this case). 

Would this be a reasonable addition, i.e. showing the lex name directly. Thanks

**Comment by moos** [comment]
`lexName` property is added in v1.1.  See lookupAdjective example in readme.

**Comment by kengz** [comment]
Awesome, thanks!
