### ISSUE TITLE
Getting synset details

### ISSUE THREAD

**Issue by mehmetilker** [moos/wordpos#12]
Is it possible to get all the details for the word in one function call ?
What I mean with details is that when we look up a word in wordnet portal we can see synset details as antonym, torponym, hypernym, sister term etc. (even frequency counts)

One way to do it, if I am not wrong iterate over ptrs node and get details for the synset by Id.
In this case @ symbol is direct hypernym I guess. (and others +, ~, $ ...)

http://wordnetweb.princeton.edu/perl/webwn?o2=1&o0=1&o8=1&o1=1&o7=1&o5=1&o9=&o6=1&o3=1&o4=1&r=2&s=accept&i=15&h=00011010001101011223022220000000#c

**Comment by moos** [comment]
Sorry for late reply. That's right -- you can loop over the ptrs and use the new (added in version 1.1)  [seek()](https://github.com/moos/wordpos#seekoffset-pos-callback) method.  You'll have to decode the [WordNet symbols](https://wordnet.princeton.edu/man/wninput.5WN.html) yourself.  

You may also want to look at [wordnet-magic](https://github.com/Planeshifter/node-wordnet-magic) which provides some of these methods, if it meets your perf requirements.

**Comment by mehmetilker** [comment]
Same problem there... I am still trying to figure out callback hell... Efficient and proper way to get definition + relations...
Plus it uses sql lite 450MB file, which I could not make it work in the cloud...

Thank you for your answer and work.
