### ISSUE TITLE
Numbers recognized as adjectives

### ISSUE THREAD

**Issue by 26medias** [moos/wordpos#13]
```
wordpos.isAdjective("17", function(bool) {
	console.log(bool); // true
});
wordpos.isAdjective("two", function(bool) {
	console.log(bool); // true
});
```

Why are numbers recognized as adjectives?

A lot of verbs are also classified as adjectives.

**Comment by moos** [comment]
Because [they are](http://wordnetweb.princeton.edu/perl/webwn?s=two&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=). That's how the underlying WordNet database works.

You can filter them out yourself before looking up.
