### ISSUE TITLE
 DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by guatedude2** [moos/wordpos#17]
Using Node 7.2.1
The followoing results in the warning:
` DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

```
const WordPOS = require('wordpos');
const wordpos = new WordPOS();
wordpos.getNouns(text).then((nouns) => {
    console.log(nouns)
})
```

Still works but it's annoying going through the logs and seeing this.

**Comment by moos** [comment]
Fixed in v1.1.1.  Thanks.
