### ISSUE TITLE
postinstall script fails with npm 5

### ISSUE THREAD

**Issue by julien-c** [moos/wordpos#19]
```
> wordpos@1.1.2 postinstall /Users/user/devel/project/node_modules/wordpos
> node tools/stat.js --no-stats index.adv index.adj index.verb index.noun

fs.js:896
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/user/devel/project/node_modules/wordpos/node_modules/wordnet-db/dict'
    at Object.fs.readdirSync (fs.js:896:18)
    at Object.<anonymous> (/Users/user/devel/project/node_modules/wordpos/node_modules/wordnet-db/index.js:4:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by julien-c** [comment]
PS: I can confirm that the issue is with npm 5, *not* node 8.

If I fix it, any way this can be merged quickly? (forked npm modules are a pain to setup in a project...)

**Comment by mehmetilker** [comment]
@julien-c  have you found a solution ?

**Comment by julien-c** [comment]
Nope, no reply from @moos so far

**Comment by benhjames** [comment]
Installing with `yarn` instead of `npm` works fine for a quick workaround!

**Comment by benhjames** [comment]
I made an issue here: npm/npm#17073

**Comment by julien-c** [comment]
Yay thanks for the investigation @benhjames great job!

**Comment by moos** [comment]
Sorry for belated reply -- and thanks for investigating and filing the issue on npm 5.  Not sure how I can unblock anyone running into this issue.  Let's home npm folks will issue a patch soon.

**Comment by julien-c** [comment]
Maybe in the meantime ship a untarred version of `wordnet-db`, or temporarily link to my fork as a dependency? https://github.com/julien-c/wordnet-db

**Comment by moos** [comment]
After a failed attempt at polling for the wordnet-db dict/ folder, I've gone with @julien-c's recommendation of checking in the exploded dict/ files in wordnet-db until there is a fix for npm.

Please try re-installing.

**Comment by julien-c** [comment]
Yes, worked well.

**Comment by moos** [comment]
Thanks.
