### ISSUE TITLE
Local package.json exists, but node_modules missing, did you mean to install?

### ISSUE THREAD

**Issue by hubert-luc** [moos/wordpos#27]
I can't install wordpos, I tried to install again npm, doesn't help, also i can install every other npm module, just not wordpos. I have node modules, everything other is working.

npm install -g wordpos

> wordpos@2.0.0-beta postinstall C:\Users\stulejka\Desktop\programowanie\testApp\node_modules\wordpos
> npm run postinstall-web && npm run postinstall-node

> wordpos@2.0.0-beta postinstall-web C:\Users\stulejka\Desktop\programowanie\testApp\node_modules\wordpos
> node scripts/makeJsonDict.js index data

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'C:\Users\stulejka\Desktop\programowanie\testApp\node_modules\wordpos\scripts\makeJsonDict.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpos@2.0.0-beta postinstall-web: `node scripts/makeJsonDict.js index data`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpos@2.0.0-beta postinstall-web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stulejka\AppData\Roaming\npm-cache\_logs\2019-05-29T16_05_21_877Z-debug.log
npm WARN testApp@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpos@2.0.0-beta postinstall: `npm run postinstall-web && npm run postinstall-node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpos@2.0.0-beta postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stulejka\AppData\Roaming\npm-cache\_logs\2019-05-29T16_05_22_853Z-debug.log

**Comment by moos** [comment]
Ah, my bad -- didn't add the "beta" tag.  Please try again and you should get the latest 1.2 version.
