### ISSUE TITLE
ReferenceError: ES6_IMPORT is not defined

### ISSUE THREAD

**Issue by hjhimanshu01** [moos/wordpos#33]
Hi there, i'm trying to import wordpos in a react project and I'm not sure that I'm doing it the right and and getting this error. `ReferenceError: ES6_IMPORT is not defined`, 
[link to file in your repo](https://github.com/moos/wordpos/blob/master/src/browser/baseFile.js#L44)
Please can you tell me the exact way to use it with ES6

**Comment by moos** [comment]
See [wordpos-web](https://github.com/moos/wordpos-web) for usage in a web environment. 

FYI: ES6_IMPORT is a placeholder that is replaced by a post build script defined in package.json.

**Comment by hjhimanshu01** [comment]
@moos , Thanks for the info!
