### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ocket8888** [moos/wordpos#38]
I can't import this in my Angular project, the import fails.

**Comment by moos** [comment]
It would help to paste the failure message.
Also if you're using this in the browser, see  [wordpos-web](https://github.com/moos/wordpos-web).

**Comment by ocket8888** [comment]
Error message:
```
ERROR in ./node_modules/wordpos/src/browser/index.js 26:10
Module parse failed: Unexpected token (26:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| class WordPOS {
| 
>   options = {};
| 
|   constructor(config) {
```
That's using `wordpos` - which has `browser/` files and says in its description

> wordpos is a set of *fast* part-of-speech (POS) utilities for Node.js **and** browser using fast lookup in the WordNet database.

So I figured it'd work in the browser. But anyway, using `wordpos-web` I get
```
ERROR in src/app/utils.ts:1:21 - error TS2307: Cannot find module 'wordpos-web'.

1 import { POS } from "wordpos-web";
                      ~~~~~~~~~~~~~
```

IDK if `POS` exists within the package, haven't gotten that far since the import fails.

**Comment by moos** [comment]
I haven't tried this with import -- that will depend on your webpack settings.  See the README for the recommended usage.  The demo samples should be helpful  as well.

**Comment by ocket8888** [comment]
So this is "wontfix" - you don't want to support Typescript?

**Comment by moos** [comment]
Correct -- you should still be able to use this by tweaking your webpack config.

**Comment by ocket8888** [comment]
I don't see anything about webpack in either repository's README - tweak how?

**Comment by ocket8888** [comment]
For anyone else with a similar use-case, I was able to satisfy my needs with [`compromise`](https://github.com/spencermountain/compromise) instead.
