### ISSUE TITLE
Words like "get" or "take" are throwing errors

### ISSUE THREAD

**Issue by JoshLDowns** [moos/wordpos#41]
Hello!  I am trying to use this library to build a text adventure.  Verbs like "get" and "take" are very integral to the game, but when I run them in a sentence through getPOS, they don't show up in any of the returned arrays.  If I try to send them alone as a string:
`wordpos.getPOS("take")`
I get the following error:
`TypeError: Cannot read property 'toLowerCase' of undefined
    at normalize (/Users/joshuadowns/Code/Personal/mern-text-adventure/node_modules/wordpos/src/util.js:32:15)`

I've also tried running them through getVerbs() with the same errors.  When I visit wordnet and run searches for the words, they come up as expected.  Any ideas?

**Comment by moos** [comment]
Thank you for reporting. It should be fixed now in v2.1.
