### ISSUE TITLE
Confusion on Output -- 'is' isn't a verb?

### ISSUE THREAD

**Issue by mcory** [moos/wordpos#8]
I know you don't have a ton of control over how the results are generated (i.e. comes from Natural and/or WordNet db), so don't know if this is the right place to talk about this. Basicall, using a very simple input sentence "the ball is red", I get the following output:

```
{ nouns: [ 'ball', 'red' ],
  verbs: [ 'ball' ],
  adjectives: [ 'red' ],
  adverbs: [],
  rest: [ 'is', 'the' ] }
```

I did a search on WordNet's site, and it does show "is" as a verb (after a few other entries that seem to be based on acronymns or whatever). Again, not sure if this is on wordpos or Natural or whatever, but figured I'd throw it out for you.

**Comment by moos** [comment]
"a ton of control" is an huge understatement.  I have 0 control! You're quite right and I get the same results. The word "is" is not in the raw WNdb files.  If you notice in the [results on WordNet](http://wordnetweb.princeton.edu/perl/webwn?s=is), the word "is" isn't actually shown either -- only its relation to other words which I believe they must be doing additional lookup in other sources.

A word of caution, both "is" and "the" are also [stopwords](https://github.com/NaturalNode/natural/blob/master/lib/natural/util/stopwords.js) which are excluded by default.  To stop excluding them, pass {stopwords: false} to the constructor.  See the main page for e.g.
